spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: tu-client-id
            client-secret: tu-client-secret
            redirect-uri: http://localhost:8080/login/oauth2/code/google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth




